### ISSUE TITLE
Position cursor in text-fields

### ISSUE THREAD

**Issue by AdityaChaudhary18** [AdityaChaudhary18/Medonate#2]
Position cursor in sign-up individual page to left-alignment.

**Comment by Kaushals112** [comment]
i am new to open source.can you assign this task.

**Comment by VanshKela** [comment]
Can I take this issue?

**Comment by AdityaChaudhary18** [comment]
> Can I take this issue?

I will assign this issue to you @VanshKela

**Comment by AdityaChaudhary18** [comment]
> i am new to open source.can you assign this task.

@Kaushals112 Look out for next issues

**Comment by AdityaChaudhary18** [comment]
Issue resolved
