### ISSUE TITLE
Add Spacing using SizedBox

### ISSUE THREAD

**Issue by AdityaChaudhary18** [AdityaChaudhary18/Medonate#4]
Add 3% height above the text "Institution Registration" in SignUp page for Institution using sizer dependency.

**Comment by Devank-Sachdeva** [comment]
can you please assign this to me . I want to work on it

**Comment by Devank-Sachdeva** [comment]
@AdityaChaudhary18 can you please review it and tell me if it requires any changes.

**Comment by VanshKela** [comment]
Can I take this issue?

**Comment by AdityaChaudhary18** [comment]
@Devank-Sachdeva Look out for more issues as of now.

**Comment by AdityaChaudhary18** [comment]
@VanshKela I have assigned you this issue.
