### ISSUE TITLE
Add Padding in Log In page

### ISSUE THREAD

**Issue by AdityaChaudhary18** [AdityaChaudhary18/Medonate#7]
Add 1% padding below log in button to adjust the UI.

**Comment by siddhesh-desai** [comment]
Hey @AdityaChaudhary18, I would like to work on this. Please assign it to me.

**Comment by Mirza-Hassan** [comment]
@AdityaChaudhary18 Please assign it to me.

**Comment by VanshKela** [comment]
Can I take this Issue

**Comment by AdityaChaudhary18** [comment]
Sure @VanshKela

**Comment by AdityaChaudhary18** [comment]
@VanshKela Thanks for the PR, will close #7 .
